//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CGWork.rc
//
#define IDDEFAULTS                      3
#define ID_DEFAULT_COLORS_BUTTON        3
#define ID_DEFAULT_FINENESS             3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CGWorkTYPE                  129
#define IDD_LIGHTS_DLG                  134
#define IDD_MATERIAL_DLG                136
#define IDD_MOUSE_SENSITIVITY_DIALOG    139
#define IDD_COLOR_PICKER_DIALOG         144
#define IDD_FINENESS_DIALOG             146
#define IDR_FACE_NORMALS                148
#define IDR_VERTEX_NORMALS              149
#define IDD_SELECT_OBJECT_DIALOG        151
#define IDD_PERSPECTIVE_SETTINGS        152
#define IDD_BACKGROUND_IMAGE_DIALOG     153
#define IDD_TOPNG_FILE_DIALOG           155
#define IDR_RECORD_BAR                  161
#define IDD_ANIMATION_PLAYER_DIALOG     164
#define IDC_LIGHT_SPACE                 1010
#define IDC_RADIO_LIGHT1                1017
#define IDC_RADIO_LIGHT2                1018
#define IDC_RADIO_LIGHT3                1019
#define IDC_RADIO_LIGHT4                1020
#define IDC_RADIO_LIGHT5                1021
#define IDC_RADIO_LIGHT6                1022
#define IDC_RADIO_LIGHT7                1023
#define IDC_RADIO_LIGHT8                1024
#define IDC_AMBL_COLOR_R                1025
#define IDC_LIGHT_ENABLED               1026
#define IDC_AMBL_COLOR_G                1027
#define IDC_AMBL_COLOR_B                1028
#define IDC_LIGHT_COLOR_R               1029
#define IDC_LIGHT_COLOR_G               1030
#define IDC_LIGHT_COLOR_B               1031
#define IDC_LIGHT_POS_X                 1032
#define IDC_LIGHT_POS_Y                 1033
#define IDC_LIGHT_POS_Z                 1034
#define IDC_LIGHT_DIR_X                 1035
#define IDC_LIGHT_DIR_Y                 1036
#define IDC_LIGHT_DIR_Z                 1037
#define IDC_LIGHT_TYPE                  1038
#define IDC_MATERIAL_AMBIENT            1039
#define IDC_LIGHT_TYPE2                 1039
#define IDC_MATERIAL_DIFFUSE            1040
#define IDC_MATERIAL_SHININESS          1041
#define IDC_MATERIAL_SPECULAR           1042
#define IDC_TRANSLATION_SLIDER          1043
#define IDC_STATIC_LOW                  1044
#define IDC_STATIC_High                 1045
#define IDC_BACKGROUND_COLOR_STATIC     1046
#define IDC_STATIC_TRANSLATION          1047
#define IDC_BOUNDINGBOX_COLOR_STATIC    1048
#define IDC_STATIC_ROTATION             1049
#define IDC_VERTIX_NORMAL_COLOR_STATIC  1050
#define IDC_STATIC_SCALE                1051
#define IDC_FACENORMAL_COLOR_STATIC     1052
#define IDC_ROTATION_SLIDER             1053
#define IDC_MODEL_COLOR_STATIC          1054
#define IDC_SCALE_SLIDER                1055
#define IDC_BOUNDINGBOX_COLOR_BUTTON    1057
#define IDC_BACKGROUND_COLOR_BUTTON     1058
#define IDC_FINENESS_SLIDER             1059
#define IDC_BACKGROUND_IMAGE_BUTTON     1059
#define IDC_VERTIX_NORMAL_COLOR_BUTTON  1060
#define IDC_FINENESS_STATIC             1061
#define IDC_FACENORMAL_COLOR_BUTTON     1062
#define IDC_MODEL_COLOR_BUTTON          1063
#define IDC_ORIGINAL_MODEL_COLOR_BUTTON 1064
#define IDC_EDIT_ZNEAR                  1065
#define IDC_EDIT_FOV                    1066
#define IDC_EDIT_ZFAR                   1067
#define IDC_OBJECT_COMBO                1068
#define IDC_SINGLE_INSTRUCTIONS_STATIC1 1069
#define IDC_SINGLE_INSTRUCTIONS_STATIC2 1070
#define IDC_SelectTitle_STATIC          1071
#define IDC_LOAD_IMAGE_BUTTON           1072
#define IDC_RADIO_NONE                  1073
#define IDC_RADIO_STRETCH               1074
#define IDC_BUTTON_RENDERTO             1074
#define IDC_RADIO_REPEAT                1075
#define IDC_EDIT_FILE_PATH              1075
#define IDC_STATIC_RENDERTO             1076
#define IDC_STATIC_WIDTH                1077
#define IDC_EDIT_WIDTH                  1078
#define IDC_STATIC_HEIGHT               1079
#define IDC_EDIT_HEIGHT                 1080
#define IDC_BUTTON_DEFAULT_SIZE         1081
#define IDC_BUTTON_CANCEL_RENDERTO_FILE 1082
#define IDC_STATIC_DIFFUSE              1083
#define IDC_STATIC_SPECULAR             1084
#define IDC_LIGHT_DIFFUSE_INTENSITY     1085
#define IDC_LIGHT_SPECULAR_INTENSITY    1086
#define IDC_STATIC_SPECULAR2            1087
#define IDC_LIGHT_AMBIENT_INTENSITY     1088
#define IDC_LIGHT_COSINE_FACTOR         1089
#define IDC_DYNAMIC_RANGE               1090
#define IDC_SPOT_LIGHT_ANGLE            1091
#define IDC_SHADOW_TYPE                 1092
#define IDC_STATIC_RENDER_MODE          1093
#define IDC_STATIC_DIFFUSE2             1094
#define IDC_SHADOW_FAR                  1095
#define IDC_STATIC_DIFFUSE3             1096
#define IDC_SHADOW_NEAR                 1097
#define IDC_STATIC_DIFFUSE4             1098
#define IDC_SHADOW_RESOLUTION           1099
#define IDC_STATIC_SPEED                1100
#define IDC_SPIN_SPEED                  1101
#define IDC_COMBO_RENDER_MODE           1102
#define IDC_STATIC_STEP                 1103
#define IDC_SPIN_STEP                   1104
#define IDC_EDIT_SPEED                  1105
#define IDC_EDIT1                       1106
#define IDC_EDIT_STEP                   1106
#define IDC_CHECK1                      1107
#define IDC_CHECK_REWIND                1107
#define ID_FILE_LOAD                    32771
#define ID_VIEW_ORTHOGRAPHIC            32772
#define ID_VIEW_PERSPECTIVE             32773
#define ID_ACTION_ROTATE                32774
#define ID_ACTION_TRANSLATE             32775
#define ID_ACTION_SCALE                 32776
#define ID_AXIS_X                       32777
#define ID_AXIS_Y                       32778
#define ID_AXIS_Z                       32779
#define ID_LIGHT_SHADING_FLAT           32781
#define ID_LIGHT_SHADING_GOURAUD        32782
#define ID_LIGHT_CONSTANTS              32783
#define ID_ANIM_PLAY                    32793
#define ID_ANIM_CLEAR                   32794
#define ID_ANIM_SNAPSHOT                32795
#define ID_BUTTON_SUBDIVIDE             32797
#define ID_OPTIONS_PERSPECTIVECONTROL   32798
#define ID_OPTIONS_MOUSESENSITIVITY     32799
#define ID_VIEW_SPACE                   32802
#define ID_OBJECT_SPACE                 32804
#define ID_AXIS_XY                      32807
#define ID_AXIS_XYZ                     32808
#define ID_AXIS_MIXEDXY                 32811
#define ID_AXIS_UNIFORMXYZ              32812
#define ID_OPTIONS_COLORPICKER          32813
#define ID_BUTTON                       32814
#define ID_OPTIONS_POLYGONALFINENESS    32815
#define ID_FACE_NORMALS                 32818
#define ID_VERTEX_NORMALS               32819
#define ID_PERSPECCTIVE_SETTINGS        32820
#define ID_OPTIONS_PERSPECTIVESETTINGS  32821
#define ID_OPTIONS_PERSID_PECTIVESETTINGS 32822
#define ID_PERS                         32823
#define ID_OPTIONS_SELECTOBJECT         32824
#define ID_OPTIONS_BACKGROUNDIMAGE      32825
#define ID_RENDER_RENDERMODE            32826
#define ID_RENDERMODE_WIREFRAME         32827
#define ID_RENDERMODE_SOLID             32828
#define ID_RENDER_ONSCREEN              32829
#define ID_RENDER_TOFILE                32830
#define ID_FILE_SAVEASPNG               32832
#define ID_SHADING_PHONG                32833
#define ID_LIGHT_SHADING_PHONG          32834
#define ID_VIEW_BACKFACECULLING         32835
#define ID_VIEW_BACK                    32836
#define ID_VIEW_INVERTNORMALS           32837
#define ID_VIEW_ALWAYSCALCULATETHEVERTICES 32838
#define ID_VIEW_ALWAYSCALCULATEVERTICESNORMALS 32839
#define ID_VIEW_SILHOUETTEHIGHLIGHTING  32840
#define ID_RECORD_BUTTON                32846
#define ID_PLAY_BUTTON                  32847
#define ID_BUTTON32850                  32850
#define ID_BUTTON32851                  32851
#define ID_VIEW_                        32852
#define ID_VIEW_RECORDINGBAR            32853
#define ID_BUTTON32855                  32855
#define ID_BUTTON32859                  32859
#define ID_BUTTON32862                  32862
#define ID_BUTTON32864                  32864
#define ID_BUTTON32866                  32866
#define ID_BUTTON32868                  32868
#define ID_BUTTON32869                  32869
#define ID_STOP_RECORDING_BUTTON        32870
#define ID_SNAPSHOT_BUTTON              32871
#define ID_SAVE_RECORD_BUTTON           32872
#define ID_DISCARD_RECORD_BUTTON        32873
#define ID_PAUSE_BUTTON                 32874
#define ID_NEXT_FRAME_BUTTON            32875
#define ID_RESET_PLAYER_BUTTON          32876

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
