/*****************************************************************************
* All attributes by Ids definitions in IRIT.				     *
******************************************************************************
* (C) Gershon Elber, Technion, Israel Institute of Technology                *
******************************************************************************
* Written by:  Gershon Elber				Ver 0.2, Jan. 2019   *
*****************************************************************************/

#ifndef IRIT_MISC_ATTR_ID_H
#define IRIT_MISC_ATTR_ID_H

/* Every attribute should placed here, at the end, and in misc_attr_defs.c. */
/* Existing attributes IDs are NOT to be changed - binary files will break. */

#define IRIT_ATTR_ID_PREFIX       IRIT_ATTR_ID_   /* Irit attribute prefix. */
#define IRIT_ATTR_CREATE_ID(Attr) IRIT_ATTR_ID_##Attr      /* Irit attr ID. */
#define IRIT_ATTR_INVALID_ATTR_ID (IRIT_ATTR_CREATE_ID(___INVALID_ATTR))
#define IRIT_ATTR_TERMINATE_ID (IRIT_ATTR_CREATE_ID(___INVALID_TERMINATOR))
#define IRIT_ATTR_ID_IS_INVALID_ATTR_ID(AttrID) \
			              ((AttrID) == IRIT_ATTR_INVALID_ATTR_ID)
#define IRIT_ATTR_ID_GET_NAME(AttrID) \
                                    (_IPAttrIDDefTable[(int) AttrID].AttrName)

/*****************************************************************************
* Attributes - the attributes' table.					     *
*****************************************************************************/
typedef struct IPAttrIDDefStruct {
    int AttrID;
    const char *AttrName;
} IPAttrIDDefStruct;

/* Every attribute should placed here, at the end, and in misc_attr_defs.c. */
/* Existing attributes IDs are NOT to be changed - binary files will break. */

/* Naming convention for attribute key ids:  one word all lower case, while */
/* multiple words are each capitalized.					    */

typedef enum {
    IRIT_ATTR_CREATE_ID(___AttributeDefTableBase),
    IRIT_ATTR_CREATE_ID(___BASE_ATTR),
    IRIT_ATTR_CREATE_ID(___INVALID_ATTR),
    IRIT_ATTR_CREATE_ID(___INVALID_TERMINATOR), 
    IRIT_ATTR_CREATE_ID(___TEMP1),                 /* Temporary attributes. */
    IRIT_ATTR_CREATE_ID(___TEMP2),

    IRIT_ATTR_CREATE_ID(_adap_iso),                   /* Hidden attributes. */
    IRIT_ATTR_CREATE_ID(_Angle),
    IRIT_ATTR_CREATE_ID(_animation_mat),
    IRIT_ATTR_CREATE_ID(_AttrPerturbed),
    IRIT_ATTR_CREATE_ID(_BjctPoly),
    IRIT_ATTR_CREATE_ID(_bndry),
    IRIT_ATTR_CREATE_ID(_coerced),
    IRIT_ATTR_CREATE_ID(_collapse),
    IRIT_ATTR_CREATE_ID(_contours),
    IRIT_ATTR_CREATE_ID(_CosNrmlMaxDev),
    IRIT_ATTR_CREATE_ID(_creator_aux_fi_),
    IRIT_ATTR_CREATE_ID(_creator_fi_),
    IRIT_ATTR_CREATE_ID(_CrvIdx),
    IRIT_ATTR_CREATE_ID(_csc),
    IRIT_ATTR_CREATE_ID(_ctlmesh),
    IRIT_ATTR_CREATE_ID(_DefFac),
    IRIT_ATTR_CREATE_ID(_disconts),
    IRIT_ATTR_CREATE_ID(_DistHandle),
    IRIT_ATTR_CREATE_ID(_DmnSize),
    IRIT_ATTR_CREATE_ID(_DoNotSelect),
    IRIT_ATTR_CREATE_ID(_EdgeDist),
    IRIT_ATTR_CREATE_ID(_EndPts),
    IRIT_ATTR_CREATE_ID(_EntityNum),
    IRIT_ATTR_CREATE_ID(_EntityNumEucCrv),
    IRIT_ATTR_CREATE_ID(_EntityNumFace),
    IRIT_ATTR_CREATE_ID(_EntityNumManifold),
    IRIT_ATTR_CREATE_ID(_EntityNumSrf),
    IRIT_ATTR_CREATE_ID(_EntityNumTcrvs),
    IRIT_ATTR_CREATE_ID(_EntityNumTLoop),
    IRIT_ATTR_CREATE_ID(_EntityNumTVecs),
    IRIT_ATTR_CREATE_ID(_EntityNumUv1crv),
    IRIT_ATTR_CREATE_ID(_EntityNumUv2crv),
    IRIT_ATTR_CREATE_ID(_Error),
    IRIT_ATTR_CREATE_ID(_ETGradient),
    IRIT_ATTR_CREATE_ID(_EvalCurv),
    IRIT_ATTR_CREATE_ID(_ExplAnimVrtcs),
    IRIT_ATTR_CREATE_ID(_ExtraSrf),
    IRIT_ATTR_CREATE_ID(_geometry),
    IRIT_ATTR_CREATE_ID(_HighlightLnData),
    IRIT_ATTR_CREATE_ID(_ImageAlpha),
    IRIT_ATTR_CREATE_ID(_ImageHeight),
    IRIT_ATTR_CREATE_ID(_ImageScaleX),
    IRIT_ATTR_CREATE_ID(_ImageScaleY),
    IRIT_ATTR_CREATE_ID(_ImageTexID),
    IRIT_ATTR_CREATE_ID(_ImageTexIDOld),
    IRIT_ATTR_CREATE_ID(_ImageTexture),
    IRIT_ATTR_CREATE_ID(_ImageTextureLoaded),
    IRIT_ATTR_CREATE_ID(_ImageWidth),
    IRIT_ATTR_CREATE_ID(_ImpStrokes),
    IRIT_ATTR_CREATE_ID(_InflectPt),
    IRIT_ATTR_CREATE_ID(_Input),
    IRIT_ATTR_CREATE_ID(_inQueue),
    IRIT_ATTR_CREATE_ID(_Inside),
    IRIT_ATTR_CREATE_ID(_Inter),
    IRIT_ATTR_CREATE_ID(_Inverse),
    IRIT_ATTR_CREATE_ID(_IPO2IMtl),
    IRIT_ATTR_CREATE_ID(_isolines),
    IRIT_ATTR_CREATE_ID(_IsolinesHiRes),
    IRIT_ATTR_CREATE_ID(_IsolinesLoRes),
    IRIT_ATTR_CREATE_ID(_isophotes),
    IRIT_ATTR_CREATE_ID(_IsVisible),
    IRIT_ATTR_CREATE_ID(_ITCIndex),
    IRIT_ATTR_CREATE_ID(_ITPIndex),
    IRIT_ATTR_CREATE_ID(_ITSIndex),
    IRIT_ATTR_CREATE_ID(_KnotLines),
    IRIT_ATTR_CREATE_ID(_KnotRefineMatrix),
    IRIT_ATTR_CREATE_ID(_MappedObject),
    IRIT_ATTR_CREATE_ID(_MaxUWidth),
    IRIT_ATTR_CREATE_ID(_MaxX),
    IRIT_ATTR_CREATE_ID(_MaxXIndx),
    IRIT_ATTR_CREATE_ID(_MeltF),
    IRIT_ATTR_CREATE_ID(_model),
    IRIT_ATTR_CREATE_ID(_ModelTSrfs),
    IRIT_ATTR_CREATE_ID(_MovieAlpha),
    IRIT_ATTR_CREATE_ID(_MovieHeight),
    IRIT_ATTR_CREATE_ID(_MovieIdx),
    IRIT_ATTR_CREATE_ID(_MovieLength),
    IRIT_ATTR_CREATE_ID(_MovieRestart),
    IRIT_ATTR_CREATE_ID(_MovieScaleX),
    IRIT_ATTR_CREATE_ID(_MovieScaleY),
    IRIT_ATTR_CREATE_ID(_MovieTexID),
    IRIT_ATTR_CREATE_ID(_MovieTexture),
    IRIT_ATTR_CREATE_ID(_MovieTimes),
    IRIT_ATTR_CREATE_ID(_MovieWidth),
    IRIT_ATTR_CREATE_ID(_MtchedEnd),
    IRIT_ATTR_CREATE_ID(_MtchedStrt),
    IRIT_ATTR_CREATE_ID(_NoDeleteOnClear),
    IRIT_ATTR_CREATE_ID(_NormalSrf),
    IRIT_ATTR_CREATE_ID(_NoSubdivDirs),
    IRIT_ATTR_CREATE_ID(_OnBndry),
    IRIT_ATTR_CREATE_ID(_OrientDisjoint),
    IRIT_ATTR_CREATE_ID(_OrigCrv),
    IRIT_ATTR_CREATE_ID(_OrigObj),
    IRIT_ATTR_CREATE_ID(_OrigPoly),
    IRIT_ATTR_CREATE_ID(_OrigTVPtr),
    IRIT_ATTR_CREATE_ID(_OrigX),
    IRIT_ATTR_CREATE_ID(_OrigY),
    IRIT_ATTR_CREATE_ID(_OrigZ),
    IRIT_ATTR_CREATE_ID(_periodic),
    IRIT_ATTR_CREATE_ID(_Perturbed),
    IRIT_ATTR_CREATE_ID(_PerturbedID),
    IRIT_ATTR_CREATE_ID(_PIdx),
    IRIT_ATTR_CREATE_ID(_PointIDs),
    IRIT_ATTR_CREATE_ID(_polygons),
    IRIT_ATTR_CREATE_ID(_PolygonsHiRes),
    IRIT_ATTR_CREATE_ID(_PolygonsLoRes),
    IRIT_ATTR_CREATE_ID(_Psec),
    IRIT_ATTR_CREATE_ID(_PSecEucCrv),
    IRIT_ATTR_CREATE_ID(_PSecFace),
    IRIT_ATTR_CREATE_ID(_PSecManifold),
    IRIT_ATTR_CREATE_ID(_PSecSrf),
    IRIT_ATTR_CREATE_ID(_PSecTCrvs),
    IRIT_ATTR_CREATE_ID(_PSecTLoop),
    IRIT_ATTR_CREATE_ID(_PSecTVecs),
    IRIT_ATTR_CREATE_ID(_PSecUV1Crv),
    IRIT_ATTR_CREATE_ID(_PSecUV2Crv),
    IRIT_ATTR_CREATE_ID(_ptsktch),
    IRIT_ATTR_CREATE_ID(_res_sketch),
    IRIT_ATTR_CREATE_ID(_RflctCircData),
    IRIT_ATTR_CREATE_ID(_RflctLnData),
    IRIT_ATTR_CREATE_ID(_RflctLnDataLHS),
    IRIT_ATTR_CREATE_ID(_RflctLnDataRHS),
    IRIT_ATTR_CREATE_ID(_SampPts),
    IRIT_ATTR_CREATE_ID(_SegIdx),
    IRIT_ATTR_CREATE_ID(_SFCTransInfo),
    IRIT_ATTR_CREATE_ID(_ShdStrokes),
    IRIT_ATTR_CREATE_ID(_silh),
    IRIT_ATTR_CREATE_ID(_SilStrokes),
    IRIT_ATTR_CREATE_ID(_sketches),
    IRIT_ATTR_CREATE_ID(_sort),
    IRIT_ATTR_CREATE_ID(_SortDir),
    IRIT_ATTR_CREATE_ID(_SphCones),
    IRIT_ATTR_CREATE_ID(_SplitPts),
    IRIT_ATTR_CREATE_ID(_srf_polys),
    IRIT_ATTR_CREATE_ID(_SrfIdx),
    IRIT_ATTR_CREATE_ID(_SrfsOnly),
    IRIT_ATTR_CREATE_ID(_subTrims),
    IRIT_ATTR_CREATE_ID(_transformed),
    IRIT_ATTR_CREATE_ID(_tricirc),
    IRIT_ATTR_CREATE_ID(_TrInfo),
    IRIT_ATTR_CREATE_ID(_tsrf),
    IRIT_ATTR_CREATE_ID(_TVIndex),
    IRIT_ATTR_CREATE_ID(_TVPl),
    IRIT_ATTR_CREATE_ID(_used),
    IRIT_ATTR_CREATE_ID(_UserGCCloseCirc),
    IRIT_ATTR_CREATE_ID(_Uv),
    IRIT_ATTR_CREATE_ID(_uvcrv),
    IRIT_ATTR_CREATE_ID(_uvExtrm),
    IRIT_ATTR_CREATE_ID(_uvsrf),
    IRIT_ATTR_CREATE_ID(_value),
    IRIT_ATTR_CREATE_ID(_VEIndex),
    IRIT_ATTR_CREATE_ID(_VIdx),
    IRIT_ATTR_CREATE_ID(_VMaxX),
    IRIT_ATTR_CREATE_ID(_VMdlBlendInfo),
    IRIT_ATTR_CREATE_ID(_VModel),
    IRIT_ATTR_CREATE_ID(_VModelTSrfs),
    IRIT_ATTR_CREATE_ID(_VrtxIdx),
    IRIT_ATTR_CREATE_ID(_vslist),
    IRIT_ATTR_CREATE_ID(_vst),
    IRIT_ATTR_CREATE_ID(_W_1),
    IRIT_ATTR_CREATE_ID(_WasVisited),
    IRIT_ATTR_CREATE_ID(_WasVisitedID),
    IRIT_ATTR_CREATE_ID(_x_coord_value),
    IRIT_ATTR_CREATE_ID(_ZCollidePls),
    IRIT_ATTR_CREATE_ID(_ZDepth),

    IRIT_ATTR_CREATE_ID(activated),		      /* Regular attr names. */
    IRIT_ATTR_CREATE_ID(active),
    IRIT_ATTR_CREATE_ID(AdapIsoDir),
    IRIT_ATTR_CREATE_ID(AdapIsoDist),
    IRIT_ATTR_CREATE_ID(AdapIsoMinSubdiv),
    IRIT_ATTR_CREATE_ID(AdapIsoMinSubdivLevel),
    IRIT_ATTR_CREATE_ID(adwidth),
    IRIT_ATTR_CREATE_ID(AlreadyTriang),
    IRIT_ATTR_CREATE_ID(ambient),
    IRIT_ATTR_CREATE_ID(ambient_k),
    IRIT_ATTR_CREATE_ID(AmbtRGB),
    IRIT_ATTR_CREATE_ID(AMFiber),
    IRIT_ATTR_CREATE_ID(AMFiberWidth),
    IRIT_ATTR_CREATE_ID(angle),
    IRIT_ATTR_CREATE_ID(Animatable),
    IRIT_ATTR_CREATE_ID(animation),
    IRIT_ATTR_CREATE_ID(animation_mat),
    IRIT_ATTR_CREATE_ID(AnimKeyFrames),
    IRIT_ATTR_CREATE_ID(AnimTime),
    IRIT_ATTR_CREATE_ID(area),
    IRIT_ATTR_CREATE_ID(AreaInnerProds),
    IRIT_ATTR_CREATE_ID(AreaInnerProdsID),
    IRIT_ATTR_CREATE_ID(AreaPts),
    IRIT_ATTR_CREATE_ID(AreParam),
    IRIT_ATTR_CREATE_ID(ArrowTxt),
    IRIT_ATTR_CREATE_ID(AuthoredBy),
    IRIT_ATTR_CREATE_ID(BarsInfo),
    IRIT_ATTR_CREATE_ID(BBox),
    IRIT_ATTR_CREATE_ID(BBoxSize),
    IRIT_ATTR_CREATE_ID(BDvlpIdx),
    IRIT_ATTR_CREATE_ID(BgRGB),
    IRIT_ATTR_CREATE_ID(BlnddNormal),
    IRIT_ATTR_CREATE_ID(Bndry),
    IRIT_ATTR_CREATE_ID(BndryID),
    IRIT_ATTR_CREATE_ID(BndryIn),
    IRIT_ATTR_CREATE_ID(BndryInter),
    IRIT_ATTR_CREATE_ID(BndryOut),
    IRIT_ATTR_CREATE_ID(BndryRefine),
    IRIT_ATTR_CREATE_ID(BndryTiles),
    IRIT_ATTR_CREATE_ID(Body),
    IRIT_ATTR_CREATE_ID(brilliance),
    IRIT_ATTR_CREATE_ID(BRuledIdx),
    IRIT_ATTR_CREATE_ID(BspDomainMax),
    IRIT_ATTR_CREATE_ID(BspDomainMin),
    IRIT_ATTR_CREATE_ID(BzrIndex),
    IRIT_ATTR_CREATE_ID(C1CropTol),
    IRIT_ATTR_CREATE_ID(C1DiscDir),
    IRIT_ATTR_CREATE_ID(C1Discont),
    IRIT_ATTR_CREATE_ID(C1DiscVal),
    IRIT_ATTR_CREATE_ID(CAIndex),
    IRIT_ATTR_CREATE_ID(camera),
    IRIT_ATTR_CREATE_ID(caustics),
    IRIT_ATTR_CREATE_ID(CC),
    IRIT_ATTR_CREATE_ID(CellID),
    IRIT_ATTR_CREATE_ID(center),
    IRIT_ATTR_CREATE_ID(CircR),
    IRIT_ATTR_CREATE_ID(CircX),
    IRIT_ATTR_CREATE_ID(CircY),
    IRIT_ATTR_CREATE_ID(ClipPlane),
    IRIT_ATTR_CREATE_ID(CnstrntsInfo),
    IRIT_ATTR_CREATE_ID(color),
    IRIT_ATTR_CREATE_ID(CompE3Crv),
    IRIT_ATTR_CREATE_ID(CompUVCrv),
    IRIT_ATTR_CREATE_ID(conic),
    IRIT_ATTR_CREATE_ID(conserve_energy),
    IRIT_ATTR_CREATE_ID(ContainedIn),
    IRIT_ATTR_CREATE_ID(CopyAndRemove),
    IRIT_ATTR_CREATE_ID(Corner),
    IRIT_ATTR_CREATE_ID(crand),
    IRIT_ATTR_CREATE_ID(crease_angle),
    IRIT_ATTR_CREATE_ID(critic_ar),
    IRIT_ATTR_CREATE_ID(crv_resolution),
    IRIT_ATTR_CREATE_ID(CrvArng),
    IRIT_ATTR_CREATE_ID(CrvSourceID),
    IRIT_ATTR_CREATE_ID(CtlPt),
    IRIT_ATTR_CREATE_ID(ctype),
    IRIT_ATTR_CREATE_ID(CurvContact),
    IRIT_ATTR_CREATE_ID(CurveStroke),
    IRIT_ATTR_CREATE_ID(CutIdx),
    IRIT_ATTR_CREATE_ID(CuttingTangent),
    IRIT_ATTR_CREATE_ID(CV_CV),
    IRIT_ATTR_CREATE_ID(CV_PT),
    IRIT_ATTR_CREATE_ID(cx),
    IRIT_ATTR_CREATE_ID(cy),
    IRIT_ATTR_CREATE_ID(cz),
    IRIT_ATTR_CREATE_ID(D1),
    IRIT_ATTR_CREATE_ID(D2),
    IRIT_ATTR_CREATE_ID(dash),
    IRIT_ATTR_CREATE_ID(DbgName),
    IRIT_ATTR_CREATE_ID(Depth),
    IRIT_ATTR_CREATE_ID(DepthCue),
    IRIT_ATTR_CREATE_ID(derivative),
    IRIT_ATTR_CREATE_ID(DfrmFctr),
    IRIT_ATTR_CREATE_ID(diffuse),
    IRIT_ATTR_CREATE_ID(dim),
    IRIT_ATTR_CREATE_ID(Dir),
    IRIT_ATTR_CREATE_ID(DirEntry),
    IRIT_ATTR_CREATE_ID(DirVal),
    IRIT_ATTR_CREATE_ID(DiscontAngle),
    IRIT_ATTR_CREATE_ID(dispersion),
    IRIT_ATTR_CREATE_ID(dispersion_samples),
    IRIT_ATTR_CREATE_ID(DispTextDir),
    IRIT_ATTR_CREATE_ID(DispTextDirPower),
    IRIT_ATTR_CREATE_ID(DmnBBox),
    IRIT_ATTR_CREATE_ID(DomainMax),
    IRIT_ATTR_CREATE_ID(DomainMin),
    IRIT_ATTR_CREATE_ID(dummy),
    IRIT_ATTR_CREATE_ID(DumpedInstObj),
    IRIT_ATTR_CREATE_ID(DWidth),
    IRIT_ATTR_CREATE_ID(E3Crv),
    IRIT_ATTR_CREATE_ID(E3Poly),
    IRIT_ATTR_CREATE_ID(ECConstraints),
    IRIT_ATTR_CREATE_ID(ECUvCrv),
    IRIT_ATTR_CREATE_ID(ECUvSrf),
    IRIT_ATTR_CREATE_ID(EditCrvDirectly),
    IRIT_ATTR_CREATE_ID(EditSrfDirectly),
    IRIT_ATTR_CREATE_ID(emission),
    IRIT_ATTR_CREATE_ID(EndAngle),
    IRIT_ATTR_CREATE_ID(Error),
    IRIT_ATTR_CREATE_ID(Euclid),
    IRIT_ATTR_CREATE_ID(EventType),
    IRIT_ATTR_CREATE_ID(ExecAnimParams),
    IRIT_ATTR_CREATE_ID(ExplodedAnimation),
    IRIT_ATTR_CREATE_ID(ExplodedAnimRelScale),
    IRIT_ATTR_CREATE_ID(ExtntScl),
    IRIT_ATTR_CREATE_ID(ExtntSclU),
    IRIT_ATTR_CREATE_ID(ExtntSclUMax),
    IRIT_ATTR_CREATE_ID(ExtntSclUMin),
    IRIT_ATTR_CREATE_ID(ExtntSclV),
    IRIT_ATTR_CREATE_ID(ExtntSclVMax),
    IRIT_ATTR_CREATE_ID(ExtntSclVMin),
    IRIT_ATTR_CREATE_ID(ExtntSclW),
    IRIT_ATTR_CREATE_ID(ExtntSclWMax),
    IRIT_ATTR_CREATE_ID(ExtntSclWMin),
    IRIT_ATTR_CREATE_ID(ExtremeType),
    IRIT_ATTR_CREATE_ID(fade_color),
    IRIT_ATTR_CREATE_ID(fade_distance),
    IRIT_ATTR_CREATE_ID(fade_power),
    IRIT_ATTR_CREATE_ID(FeedRate),
    IRIT_ATTR_CREATE_ID(fill),
    IRIT_ATTR_CREATE_ID(Finish),
    IRIT_ATTR_CREATE_ID(First),
    IRIT_ATTR_CREATE_ID(FitError),
    IRIT_ATTR_CREATE_ID(fourperflat),
    IRIT_ATTR_CREATE_ID(FOV),
    IRIT_ATTR_CREATE_ID(FreeMotion),
    IRIT_ATTR_CREATE_ID(Frustum),
    IRIT_ATTR_CREATE_ID(GeomIdx),
    IRIT_ATTR_CREATE_ID(GeomType),
    IRIT_ATTR_CREATE_ID(Gradient),
    IRIT_ATTR_CREATE_ID(gray),
    IRIT_ATTR_CREATE_ID(grid_shadow_props),
    IRIT_ATTR_CREATE_ID(GridSize),
    IRIT_ATTR_CREATE_ID(Halo),
    IRIT_ATTR_CREATE_ID(HasBoth),
    IRIT_ATTR_CREATE_ID(HCurv),
    IRIT_ATTR_CREATE_ID(HeatWave),
    IRIT_ATTR_CREATE_ID(hidden),
    IRIT_ATTR_CREATE_ID(HierarchyTreeIndex),
    IRIT_ATTR_CREATE_ID(HierItemExpanded),
    IRIT_ATTR_CREATE_ID(HitIdx),
    IRIT_ATTR_CREATE_ID(ID),
    IRIT_ATTR_CREATE_ID(IgesFormNum),
    IRIT_ATTR_CREATE_ID(IgesIrtOp),
    IRIT_ATTR_CREATE_ID(IgesIrtOpParam1),
    IRIT_ATTR_CREATE_ID(IgesIrtOpParam2),
    IRIT_ATTR_CREATE_ID(IgesIrtOpParam3),
    IRIT_ATTR_CREATE_ID(IgesIrtOpParam4),
    IRIT_ATTR_CREATE_ID(IgesIrtOpParam5),
    IRIT_ATTR_CREATE_ID(IgesPlane),
    IRIT_ATTR_CREATE_ID(IGESResetColor),
    IRIT_ATTR_CREATE_ID(IllustrtNoProcess),
    IRIT_ATTR_CREATE_ID(IllustrtShadeBG),
    IRIT_ATTR_CREATE_ID(Improved),
    IRIT_ATTR_CREATE_ID(Imprt),
    IRIT_ATTR_CREATE_ID(index),
    IRIT_ATTR_CREATE_ID(init),
    IRIT_ATTR_CREATE_ID(InpMdl),
    IRIT_ATTR_CREATE_ID(Input),
    IRIT_ATTR_CREATE_ID(intercrvs),
    IRIT_ATTR_CREATE_ID(Interior),
    IRIT_ATTR_CREATE_ID(InterPts),
    IRIT_ATTR_CREATE_ID(Intersected),
    IRIT_ATTR_CREATE_ID(InTriangle),
    IRIT_ATTR_CREATE_ID(Invalid),
    IRIT_ATTR_CREATE_ID(invisible),
    IRIT_ATTR_CREATE_ID(ior),
    IRIT_ATTR_CREATE_ID(IpDegenPoly),
    IRIT_ATTR_CREATE_ID(IPO2I_RES),
    IRIT_ATTR_CREATE_ID(IPO2I_SCRV),
    IRIT_ATTR_CREATE_ID(IPO2I_SP),
    IRIT_ATTR_CREATE_ID(irid),
    IRIT_ATTR_CREATE_ID(IritImgIcon),
    IRIT_ATTR_CREATE_ID(IRndrPurgedPoly),
    IRIT_ATTR_CREATE_ID(IRndrVMBeforePrspX),
    IRIT_ATTR_CREATE_ID(IRndrVMBeforePrspY),
    IRIT_ATTR_CREATE_ID(IRndrVMBeforePrspZ),
    IRIT_ATTR_CREATE_ID(IrtMdlrAuxDpnds),
    IRIT_ATTR_CREATE_ID(IrtMdlrAuxPrms),
    IRIT_ATTR_CREATE_ID(IrtMdlrDpnds),
    IRIT_ATTR_CREATE_ID(IrtMdlrPrms),
    IRIT_ATTR_CREATE_ID(IsActiveScene),
    IRIT_ATTR_CREATE_ID(IsoLevel),
    IRIT_ATTR_CREATE_ID(IsoParam),
    IRIT_ATTR_CREATE_ID(IsTrimmingVSrf),
    IRIT_ATTR_CREATE_ID(IsVisible),
    IRIT_ATTR_CREATE_ID(itexture),
    IRIT_ATTR_CREATE_ID(Jacobian),
    IRIT_ATTR_CREATE_ID(K),
    IRIT_ATTR_CREATE_ID(K1Curv),
    IRIT_ATTR_CREATE_ID(K2Curv),
    IRIT_ATTR_CREATE_ID(KCurv),
    IRIT_ATTR_CREATE_ID(kd),
    IRIT_ATTR_CREATE_ID(KeepParam),
    IRIT_ATTR_CREATE_ID(ks),
    IRIT_ATTR_CREATE_ID(LastVertex),
    IRIT_ATTR_CREATE_ID(letter),
    IRIT_ATTR_CREATE_ID(Level),
    IRIT_ATTR_CREATE_ID(light_source),
    IRIT_ATTR_CREATE_ID(limit),
    IRIT_ATTR_CREATE_ID(LnPtrn),
    IRIT_ATTR_CREATE_ID(LOD),
    IRIT_ATTR_CREATE_ID(LookAt),
    IRIT_ATTR_CREATE_ID(LSError),
    IRIT_ATTR_CREATE_ID(lTextSrf),
    IRIT_ATTR_CREATE_ID(ltexture),
    IRIT_ATTR_CREATE_ID(Material),
    IRIT_ATTR_CREATE_ID(MaxDist),
    IRIT_ATTR_CREATE_ID(MaxError),
    IRIT_ATTR_CREATE_ID(MaxZ),
    IRIT_ATTR_CREATE_ID(MdlID),
    IRIT_ATTR_CREATE_ID(MeltingAnimation),
    IRIT_ATTR_CREATE_ID(MeltingAnimDir),
    IRIT_ATTR_CREATE_ID(MeltingAnimRelScale),
    IRIT_ATTR_CREATE_ID(MenuName),
    IRIT_ATTR_CREATE_ID(metallic),
    IRIT_ATTR_CREATE_ID(MinSize),
    IRIT_ATTR_CREATE_ID(MinWeight),
    IRIT_ATTR_CREATE_ID(MinZ),
    IRIT_ATTR_CREATE_ID(Model),
    IRIT_ATTR_CREATE_ID(mov_x_key_frame),
    IRIT_ATTR_CREATE_ID(mov_y_key_frame),
    IRIT_ATTR_CREATE_ID(mov_z_key_frame),
    IRIT_ATTR_CREATE_ID(Movable),
    IRIT_ATTR_CREATE_ID(MSCap1ID),
    IRIT_ATTR_CREATE_ID(MSCap2ID),
    IRIT_ATTR_CREATE_ID(MSDfrmTVBndryU),
    IRIT_ATTR_CREATE_ID(MSDfrmTVBndryV),
    IRIT_ATTR_CREATE_ID(MSDfrmTVBndryW),
    IRIT_ATTR_CREATE_ID(MSGeomID),
    IRIT_ATTR_CREATE_ID(MshMixedElements),
    IRIT_ATTR_CREATE_ID(MshQuads),
    IRIT_ATTR_CREATE_ID(MshSamples),
    IRIT_ATTR_CREATE_ID(MSIndex),
    IRIT_ATTR_CREATE_ID(MSLclTVBndryU),
    IRIT_ATTR_CREATE_ID(MSLclTVBndryV),
    IRIT_ATTR_CREATE_ID(MSLclTVBndryW),
    IRIT_ATTR_CREATE_ID(MSTileID),
    IRIT_ATTR_CREATE_ID(MultiObjSplit),
    IRIT_ATTR_CREATE_ID(MVEuclid),
    IRIT_ATTR_CREATE_ID(MVMSInfo),
    IRIT_ATTR_CREATE_ID(Name),
    IRIT_ATTR_CREATE_ID(NCBridgeRelFeedRate),
    IRIT_ATTR_CREATE_ID(NCCntrBBox),
    IRIT_ATTR_CREATE_ID(NCCntrClip),
    IRIT_ATTR_CREATE_ID(NCCntrMaxDepthStep),
    IRIT_ATTR_CREATE_ID(NCCntrMaxMiterScale),
    IRIT_ATTR_CREATE_ID(NCCntrPreciseClip),
    IRIT_ATTR_CREATE_ID(NCCntrSlowOnPlunge),
    IRIT_ATTR_CREATE_ID(NCCommentChar),
    IRIT_ATTR_CREATE_ID(NCDownPlungeRelFeed),
    IRIT_ATTR_CREATE_ID(NCDownPlungeZLevel),
    IRIT_ATTR_CREATE_ID(NCFeedRate),
    IRIT_ATTR_CREATE_ID(NCMaxXYBridgeGap),
    IRIT_ATTR_CREATE_ID(NCMaxZBridgeGap),
    IRIT_ATTR_CREATE_ID(NCOrientAxes),
    IRIT_ATTR_CREATE_ID(NCOutputType),
    IRIT_ATTR_CREATE_ID(NCPower),
    IRIT_ATTR_CREATE_ID(NCRetractZLevel),
    IRIT_ATTR_CREATE_ID(NCReverseZ),
    IRIT_ATTR_CREATE_ID(NCTolerance),
    IRIT_ATTR_CREATE_ID(NCUnits),
    IRIT_ATTR_CREATE_ID(NCUpRetractFast),
    IRIT_ATTR_CREATE_ID(NON_TRIMMED_SRF),
    IRIT_ATTR_CREATE_ID(NonTrimmed),
    IRIT_ATTR_CREATE_ID(NonTrimmingVSrfIsoDir),
    IRIT_ATTR_CREATE_ID(NonTrimmingVSrfIsoVal),
    IRIT_ATTR_CREATE_ID(normal),
    IRIT_ATTR_CREATE_ID(NoShading),
    IRIT_ATTR_CREATE_ID(Null),
    IRIT_ATTR_CREATE_ID(num_of_isolines),
    IRIT_ATTR_CREATE_ID(NumZContours),
    IRIT_ATTR_CREATE_ID(NumZIsophotes),
    IRIT_ATTR_CREATE_ID(ObjCount),
    IRIT_ATTR_CREATE_ID(ObjectMatrix),
    IRIT_ATTR_CREATE_ID(ObjID),
    IRIT_ATTR_CREATE_ID(ObjName),
    IRIT_ATTR_CREATE_ID(ObjWrapper),
    IRIT_ATTR_CREATE_ID(OfstFld),
    IRIT_ATTR_CREATE_ID(ogl_camera_props),
    IRIT_ATTR_CREATE_ID(ogl_manager_setup),
    IRIT_ATTR_CREATE_ID(ogl_obj_anim_props),
    IRIT_ATTR_CREATE_ID(ogl_obj_props),
    IRIT_ATTR_CREATE_ID(ogl_setup),
    IRIT_ATTR_CREATE_ID(ogl_win_anim_props),
    IRIT_ATTR_CREATE_ID(ogl_win_props),
    IRIT_ATTR_CREATE_ID(OGLDL),
    IRIT_ATTR_CREATE_ID(Orient),
    IRIT_ATTR_CREATE_ID(OriginalColor),
    IRIT_ATTR_CREATE_ID(OrigSrf),
    IRIT_ATTR_CREATE_ID(OtherGroups),
    IRIT_ATTR_CREATE_ID(otherparam),
    IRIT_ATTR_CREATE_ID(OutRect),
    IRIT_ATTR_CREATE_ID(OverLapping_0),
    IRIT_ATTR_CREATE_ID(OverLapping_1),
    IRIT_ATTR_CREATE_ID(OverLapping_2),
    IRIT_ATTR_CREATE_ID(Param),
    IRIT_ATTR_CREATE_ID(Params),
    IRIT_ATTR_CREATE_ID(ParamTile),
    IRIT_ATTR_CREATE_ID(Parent),
    IRIT_ATTR_CREATE_ID(PATTRIB_TEST),
    IRIT_ATTR_CREATE_ID(phong),
    IRIT_ATTR_CREATE_ID(phong_size),
    IRIT_ATTR_CREATE_ID(Pigment),
    IRIT_ATTR_CREATE_ID(plane),
    IRIT_ATTR_CREATE_ID(PlAttr),
    IRIT_ATTR_CREATE_ID(pmovie),
    IRIT_ATTR_CREATE_ID(PointIDs),
    IRIT_ATTR_CREATE_ID(PointsInfo),
    IRIT_ATTR_CREATE_ID(PointSize),
    IRIT_ATTR_CREATE_ID(polyInd),
    IRIT_ATTR_CREATE_ID(Position),
    IRIT_ATTR_CREATE_ID(Prim1Pos),
    IRIT_ATTR_CREATE_ID(Prim2Pos),
    IRIT_ATTR_CREATE_ID(Prim3Pos),
    IRIT_ATTR_CREATE_ID(Priority),
    IRIT_ATTR_CREATE_ID(ProjectionType),
    IRIT_ATTR_CREATE_ID(Pt1),
    IRIT_ATTR_CREATE_ID(Pt2),
    IRIT_ATTR_CREATE_ID(ptexture),
    IRIT_ATTR_CREATE_ID(PTextureBijectObj),
    IRIT_ATTR_CREATE_ID(PTextureOriginalObj),
    IRIT_ATTR_CREATE_ID(PTextureTrnspClr),
    IRIT_ATTR_CREATE_ID(PtList),
    IRIT_ATTR_CREATE_ID(PtsDensity),
    IRIT_ATTR_CREATE_ID(radius),
    IRIT_ATTR_CREATE_ID(rational),
    IRIT_ATTR_CREATE_ID(RealTime),
    IRIT_ATTR_CREATE_ID(reflect),
    IRIT_ATTR_CREATE_ID(reflection),
    IRIT_ATTR_CREATE_ID(refract),
    IRIT_ATTR_CREATE_ID(regular),
    IRIT_ATTR_CREATE_ID(RegularTriang),
    IRIT_ATTR_CREATE_ID(RelFeedRate),
    IRIT_ATTR_CREATE_ID(Remove),
    IRIT_ATTR_CREATE_ID(Reparam),
    IRIT_ATTR_CREATE_ID(resolution),
    IRIT_ATTR_CREATE_ID(reversed),
    IRIT_ATTR_CREATE_ID(RflctLines),
    IRIT_ATTR_CREATE_ID(rgb),
    IRIT_ATTR_CREATE_ID(rgbDouble),
    IRIT_ATTR_CREATE_ID(RgnID),
    IRIT_ATTR_CREATE_ID(RngError),
    IRIT_ATTR_CREATE_ID(rot_x_key_frame),
    IRIT_ATTR_CREATE_ID(rot_y_key_frame),
    IRIT_ATTR_CREATE_ID(rot_z_key_frame),
    IRIT_ATTR_CREATE_ID(roughness),
    IRIT_ATTR_CREATE_ID(savable),
    IRIT_ATTR_CREATE_ID(saveable),
    IRIT_ATTR_CREATE_ID(SaveParamVals),
    IRIT_ATTR_CREATE_ID(scale),
    IRIT_ATTR_CREATE_ID(scene_name),
    IRIT_ATTR_CREATE_ID(scl_key_frame),
    IRIT_ATTR_CREATE_ID(SclrSrf),
    IRIT_ATTR_CREATE_ID(SCNrefraction),
    IRIT_ATTR_CREATE_ID(SCNsurface),
    IRIT_ATTR_CREATE_ID(SCNtexture),
    IRIT_ATTR_CREATE_ID(SDTexture),
    IRIT_ATTR_CREATE_ID(Second),
    IRIT_ATTR_CREATE_ID(selected),
    IRIT_ATTR_CREATE_ID(Semantics),
    IRIT_ATTR_CREATE_ID(SeqNum),
    IRIT_ATTR_CREATE_ID(shine),
    IRIT_ATTR_CREATE_ID(SilImp),
    IRIT_ATTR_CREATE_ID(SilImpRange),
    IRIT_ATTR_CREATE_ID(SilRGB),
    IRIT_ATTR_CREATE_ID(SilWidth),
    IRIT_ATTR_CREATE_ID(Similar),
    IRIT_ATTR_CREATE_ID(SingleSol),
    IRIT_ATTR_CREATE_ID(SkewDir),
    IRIT_ATTR_CREATE_ID(Solid),
    IRIT_ATTR_CREATE_ID(SpecPow),
    IRIT_ATTR_CREATE_ID(SpecRGB),
    IRIT_ATTR_CREATE_ID(specular),
    IRIT_ATTR_CREATE_ID(SpeedWave),
    IRIT_ATTR_CREATE_ID(SpindleSpeed),
    IRIT_ATTR_CREATE_ID(srf_cosine),
    IRIT_ATTR_CREATE_ID(SrfAdjInfo),
    IRIT_ATTR_CREATE_ID(SrfIndex),
    IRIT_ATTR_CREATE_ID(SrfReversed),
    IRIT_ATTR_CREATE_ID(StartAngle),
    IRIT_ATTR_CREATE_ID(StartVertex),
    IRIT_ATTR_CREATE_ID(StartVertxe), 
    IRIT_ATTR_CREATE_ID(Steps),
    IRIT_ATTR_CREATE_ID(stexture),
    IRIT_ATTR_CREATE_ID(stexture_bound),
    IRIT_ATTR_CREATE_ID(stexture_func),
    IRIT_ATTR_CREATE_ID(stexture_scale),
    IRIT_ATTR_CREATE_ID(StrPos),
    IRIT_ATTR_CREATE_ID(StrScale),
    IRIT_ATTR_CREATE_ID(StrSpace),
    IRIT_ATTR_CREATE_ID(SweepError),
    IRIT_ATTR_CREATE_ID(Symmetry),
    IRIT_ATTR_CREATE_ID(SymState),
    IRIT_ATTR_CREATE_ID(tan_angle),
    IRIT_ATTR_CREATE_ID(TCrvIdx),
    IRIT_ATTR_CREATE_ID(temp),
    IRIT_ATTR_CREATE_ID(test),
    IRIT_ATTR_CREATE_ID(test2),
    IRIT_ATTR_CREATE_ID(TextLineCnt),
    IRIT_ATTR_CREATE_ID(Texturable),
    IRIT_ATTR_CREATE_ID(Texturable_movie),
    IRIT_ATTR_CREATE_ID(texture),
    IRIT_ATTR_CREATE_ID(TextWordCnt),
    IRIT_ATTR_CREATE_ID(TileBndryType),
    IRIT_ATTR_CREATE_ID(TileTopo),
    IRIT_ATTR_CREATE_ID(TJunc),
    IRIT_ATTR_CREATE_ID(tool),
    IRIT_ATTR_CREATE_ID(ToolBottom),
    IRIT_ATTR_CREATE_ID(ToolNum),
    IRIT_ATTR_CREATE_ID(ToolProfile),
    IRIT_ATTR_CREATE_ID(Touchable),
    IRIT_ATTR_CREATE_ID(TraceIdx),
    IRIT_ATTR_CREATE_ID(trans),
    IRIT_ATTR_CREATE_ID(transp),
    IRIT_ATTR_CREATE_ID(TRefIdx),
    IRIT_ATTR_CREATE_ID(TrimCrvRelTol),
    IRIT_ATTR_CREATE_ID(trimsrf),
    IRIT_ATTR_CREATE_ID(TripleContact),
    IRIT_ATTR_CREATE_ID(TrivAdjIDUMax),
    IRIT_ATTR_CREATE_ID(TrivAdjIDUMin),
    IRIT_ATTR_CREATE_ID(TrivAdjIDVMax),
    IRIT_ATTR_CREATE_ID(TrivAdjIDVMin),
    IRIT_ATTR_CREATE_ID(TrivAdjIDWMax),
    IRIT_ATTR_CREATE_ID(TrivAdjIDWMin),
    IRIT_ATTR_CREATE_ID(TrivCollide),
    IRIT_ATTR_CREATE_ID(TrivID),
    IRIT_ATTR_CREATE_ID(TrivJcbBnd),
    IRIT_ATTR_CREATE_ID(TRPt),
    IRIT_ATTR_CREATE_ID(TRuledIdx),
    IRIT_ATTR_CREATE_ID(tubular),
    IRIT_ATTR_CREATE_ID(TwoLight),
    IRIT_ATTR_CREATE_ID(twoperflat),
    IRIT_ATTR_CREATE_ID(type),
    IRIT_ATTR_CREATE_ID(u_resolution),
    IRIT_ATTR_CREATE_ID(UCells),
    IRIT_ATTR_CREATE_ID(UdID),
    IRIT_ATTR_CREATE_ID(UGSelectedCrnr),
    IRIT_ATTR_CREATE_ID(UGSelectedEdge),
    IRIT_ATTR_CREATE_ID(UGSelectedFace),
    IRIT_ATTR_CREATE_ID(UIsoParam),
    IRIT_ATTR_CREATE_ID(UKnotRefineMatrix),
    IRIT_ATTR_CREATE_ID(Untrim2D),
    IRIT_ATTR_CREATE_ID(UpDir),
    IRIT_ATTR_CREATE_ID(URefIdx),
    IRIT_ATTR_CREATE_ID(UseAvg),
    IRIT_ATTR_CREATE_ID(used),
    IRIT_ATTR_CREATE_ID(UserMicroBndrySrfNrml),
    IRIT_ATTR_CREATE_ID(USteps),
    IRIT_ATTR_CREATE_ID(uv_dilation),
    IRIT_ATTR_CREATE_ID(UVCrv),
    IRIT_ATTR_CREATE_ID(uvLens),
    IRIT_ATTR_CREATE_ID(UVList),
    IRIT_ATTR_CREATE_ID(uvvals),
    IRIT_ATTR_CREATE_ID(v_resolution),
    IRIT_ATTR_CREATE_ID(value),
    IRIT_ATTR_CREATE_ID(VarWidth),
    IRIT_ATTR_CREATE_ID(VCells),
    IRIT_ATTR_CREATE_ID(vec1),
    IRIT_ATTR_CREATE_ID(vec2),
    IRIT_ATTR_CREATE_ID(vec3),
    IRIT_ATTR_CREATE_ID(VertexID),
    IRIT_ATTR_CREATE_ID(VIdxID),
    IRIT_ATTR_CREATE_ID(ViewDir),
    IRIT_ATTR_CREATE_ID(VisMapX),
    IRIT_ATTR_CREATE_ID(VisMapY),
    IRIT_ATTR_CREATE_ID(VIsoParam),
    IRIT_ATTR_CREATE_ID(VKnotRefineMatrix),
    IRIT_ATTR_CREATE_ID(VMdlBzrIndexU),
    IRIT_ATTR_CREATE_ID(VMdlBzrIndexV),
    IRIT_ATTR_CREATE_ID(VMdlBzrIndexW),
    IRIT_ATTR_CREATE_ID(VMdlFilletTrivID),
    IRIT_ATTR_CREATE_ID(VMdlPrimID),
    IRIT_ATTR_CREATE_ID(VMdlSrfID),
    IRIT_ATTR_CREATE_ID(VMdlTrivID),
    IRIT_ATTR_CREATE_ID(VRefIdx),
    IRIT_ATTR_CREATE_ID(VSheet),
    IRIT_ATTR_CREATE_ID(VSList),
    IRIT_ATTR_CREATE_ID(VSrfInvSrfId),
    IRIT_ATTR_CREATE_ID(VsrfNormalSrf),
    IRIT_ATTR_CREATE_ID(VSrfUntrimSrfs),
    IRIT_ATTR_CREATE_ID(VSteps),
    IRIT_ATTR_CREATE_ID(Vvals),
    IRIT_ATTR_CREATE_ID(w_resolution),
    IRIT_ATTR_CREATE_ID(WasInstance),
    IRIT_ATTR_CREATE_ID(widenend),
    IRIT_ATTR_CREATE_ID(width),
    IRIT_ATTR_CREATE_ID(WidthScale),
    IRIT_ATTR_CREATE_ID(windows_manager_setup),
    IRIT_ATTR_CREATE_ID(WRefIdx),
    IRIT_ATTR_CREATE_ID(wval),
    IRIT_ATTR_CREATE_ID(x),
    IRIT_ATTR_CREATE_ID(x_coord_value),
    IRIT_ATTR_CREATE_ID(y),
    IRIT_ATTR_CREATE_ID(z),
    IRIT_ATTR_CREATE_ID(ZSliceLevel),

    IRIT_ATTR_CREATE_ID(zzz_LAST_ATTR_ID)
} IPAttrIDType;

#define IRIT_ATTR_LAST_ATTR_ID	    IRIT_ATTR_CREATE_ID(zzz_LAST_ATTR_ID)

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/* Functions in misc_attr_id.c */

struct IPAttributeStruct;

void AttrIDSetColor(struct IPAttributeStruct **Attrs, int Color);
int AttrIDGetColor(const struct IPAttributeStruct *Attrs);
void AttrIDSetRGBColor(struct IPAttributeStruct **Attrs,
		       int Red,
		       int Green,
		       int Blue);
int AttrIDGetRGBColor(const struct IPAttributeStruct *Attrs,
		      int *Red,
		      int *Green,
		      int *Blue);
int AttrIDGetRGBColor2(const struct IPAttributeStruct *Attrs,
		       IPAttrIDType AttrID,
		       int *Red,
		       int *Green,
		       int *Blue);
void AttrIDSetRGBDoubleColor(struct IPAttributeStruct **Attrs,
			     double Red,
			     double Green,
			     double Blue);
int AttrIDGetRGBDoubleColor(const struct IPAttributeStruct *Attrs,
			    double *Red,
			    double *Green,
			    double *Blue);
void AttrIDSetWidth(struct IPAttributeStruct **Attrs, IrtRType Width);
IrtRType AttrIDGetWidth(const struct IPAttributeStruct *Attrs);
void AttrIDSetIntAttrib(struct IPAttributeStruct **Attrs,
			IPAttrIDType AttribID,
			int Data);
int AttrIDGetIntAttrib(const struct IPAttributeStruct *Attrs,
		       IPAttrIDType AttribID);
void AttrIDSetPtrAttrib(struct IPAttributeStruct **Attrs,
			IPAttrIDType AttribID,
			VoidPtr Data);
VoidPtr AttrIDGetPtrAttrib(const struct IPAttributeStruct *Attrs,
			   IPAttrIDType AttribID);
void AttrIDSetRefPtrAttrib(struct IPAttributeStruct **Attrs,
			   IPAttrIDType AttribID,
			   VoidPtr Data);
VoidPtr AttrIDGetRefPtrAttrib(const struct IPAttributeStruct *Attrs,
			      IPAttrIDType AttribID);
void AttrIDSetRealAttrib(struct IPAttributeStruct **Attrs,
			 IPAttrIDType AttribID,
			 IrtRType Data);
IrtRType AttrIDGetRealAttrib(const struct IPAttributeStruct *Attrs,
			     IPAttrIDType AttribID);
void AttrIDSetRealPtrAttrib(struct IPAttributeStruct **Attrs,
			    IPAttrIDType AttribID,
			    IrtRType *Data,
			    int DataLen);
IrtRType *AttrIDGetRealPtrAttrib(const struct IPAttributeStruct *Attrs,
				 IPAttrIDType AttribID);
void AttrIDSetUVAttrib(struct IPAttributeStruct **Attrs,
		       IPAttrIDType AttribID,
		       IrtRType U,
		       IrtRType V);
float *AttrIDGetUVAttrib(const struct IPAttributeStruct *Attrs,
			 IPAttrIDType AttribID);
void AttrIDSetStrAttrib(struct IPAttributeStruct **Attrs,
			IPAttrIDType AttribID,
			const char *Data);
const char *AttrIDGetStrAttrib(const struct IPAttributeStruct *Attrs,
			       IPAttrIDType AttribID);

void AttrIDFreeOneAttribute(struct IPAttributeStruct **Attrs,
			    IPAttrIDType AttrID);
void AttrIDRemoveOneAttribute(struct IPAttributeStruct **Attrs,
			      IPAttrIDType AttrID);
struct IPAttributeStruct *AttrIDFindAttribute(
					 const struct IPAttributeStruct *Attrs,
				         IPAttrIDType AttrID);
IPAttrIDType AttrIDGetAttribID(const char *AttribName);
const IPAttrIDType *AttrIDCopyValidAttrIDList(const IPAttrIDType *AttrIDs,
					      int *IsValidList);

#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif /* IRIT_MISC_ATTR_ID_H */
